- name: install mysql-db
  hosts:  db
  become: yes
  tasks:
  - name: remove mysql if already installed
    package:
      name: mysql-server
      state: absent
  - name: remove mysql data directory
    file:
      path: /var/lib/mysql
      state: absent
  - name: install mysql
    package:
      name: mysql-server
      state: present
  - name: start and enable mysql
    service:
      name: mysqld
      state: restarted
      enabled: yes
  - name: setup root password
    command: mysql_secure_installation --set-root-pass ExpenseApp@1
  - name: grant remote access to root
    command: >
      mysql -u root -e
      "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ExpenseApp@1';
      GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'ExpenseApp@1' WITH GRANT OPTION;
      FLUSH PRIVILEGES;" FLUSH PRIVILEGES;"

  
  
